import { webkit, devices } from "playwright";
const browser = await webkit.launch();
const ctx = await browser.newContext({ ...devices["iPhone 13"] });
const page = await ctx.newPage();
const errs = [];
page.on("pageerror", e => errs.push(e.message));
await page.goto("http://localhost:3000/login");
await page.fill('input[name="email"]', "pkm-tester@example.com");
await page.fill('input[name="password"]', "Test123456!");
await page.tap('button[type="submit"]');
await page.waitForURL(/\/notes/, {timeout:15000}).catch(()=>{});
await page.waitForTimeout(1200);
await page.tap('button[aria-label="New note"]');
await page.waitForURL(/\/notes\/[0-9a-f-]+/, {timeout:15000});
await page.waitForSelector(".ProseMirror", {timeout:8000});
await page.tap('input[placeholder="Untitled"]');
await page.keyboard.type("typed title");
const t = await page.inputValue('input[placeholder="Untitled"]');
await page.tap(".ProseMirror");
await page.keyboard.type("typed body");
const b = await page.locator(".ProseMirror").innerText();
console.log("title value:", JSON.stringify(t));
console.log("body value:", JSON.stringify(b.slice(0,30)));
console.log("errors:", errs.length ? errs.slice(0,3) : "none");
await browser.close();
